"""Create tables

Revision ID: 62509ab8f682
Revises: 
Create Date: 2022-11-06 01:51:30.430410

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '62509ab8f682'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group',
    sa.Column('id_group', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=25), nullable=False),
    sa.PrimaryKeyConstraint('id_group')
    )
    op.create_table('subject',
    sa.Column('id_subject', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('credits', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id_subject')
    )
    op.create_table('user',
    sa.Column('id_user', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=25), nullable=False),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('first_name', sa.String(length=25), nullable=False),
    sa.Column('last_name', sa.String(length=25), nullable=False),
    sa.Column('email', sa.String(length=45), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.PrimaryKeyConstraint('id_user'),
    sa.UniqueConstraint('username')
    )
    op.create_table('student',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_of_birthday', sa.Date(), nullable=False),
    sa.Column('date_of_entry', sa.Date(), nullable=False),
    sa.Column('date_of_graduation', sa.Date(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group.id_group'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('teacher',
    sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('date_of_employment', sa.Date(), nullable=False),
    sa.Column('qualification', sa.String(length=75), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id_user'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('mark',
    sa.Column('id_mark', sa.Integer(), nullable=False),
    sa.Column('mark', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('subject_id', sa.Integer(), nullable=True),
    sa.Column('student_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['subject.id_subject'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['teacher_id'], ['teacher.user_id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id_mark')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mark')
    op.drop_table('teacher')
    op.drop_table('student')
    op.drop_table('user')
    op.drop_table('subject')
    op.drop_table('group')
    # ### end Alembic commands ###
